version: '3'
services:

  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      
volumes:
 mongodb:
